const themeConfig = {
  token: {
    colorPrimary: '#86fc70',
    colorInfo: '#86fc70',
    colorSuccess: '#1aca75',
    colorError: '#fd305d',
    colorLink: '#3c7bf4',
    colorTextBase: '#222222',
    borderRadius: 8,
    wireframe: false,
  },
  components: {
    Pagination: {
      itemActiveBg: '#86fc70',
      colorPrimary: '#222222',
      borderRadius: 4,
      lineType: 'nul',
      colorBgTextActive: '#222222',
      colorPrimaryHover: '#222222',
      itemSize: 28,
    },
    Button: {
      borderRadius: 40,
      defaultColor: '#222222',
      primaryColor: '#222222',
      defaultBorderColor: '#f4f4f4',
      algorithm: true,
      colorBorder: '#d9d9d9',
      defaultHoverBorderColor: '#f4f4f4',
      defaultHoverColor: '#222222',
      defaultHoverBg: '#f4f4f4',
      defaultActiveBorderColor: '#f4f4f4',
      defaultActiveColor: '#222222',
      defaultBg: '#f4f4f4',
      defaultActiveBg: '#f9f9f9',
      colorTextDisabled: '#ffffff',
      colorBgContainerDisabled: '#d5d5d5',
    },
    Checkbox: {
      colorWhite: '#222222',
      borderRadiusSM: 4,
    },
    Input: {
      paddingInline: 12,
      paddingBlock: 9,
      colorErrorBg: '#ff638533',
      colorBorder: '#f8f8f8',
      addonBg: '#f8f8f8',
      activeBg: '#f8f8f8',
      hoverBg: '#f8f8f8',
    },
    InputNumber: {
      paddingInline: 12,
      paddingBlock: 9,
      colorErrorBg: 'rgba(255,99,133,0.2)',
      colorBorder: 'rgb(248,248,248)',
      addonBg: 'rgb(248,248,248)',
      activeBg: 'rgb(248,248,248)',
      hoverBg: 'rgb(248,248,248)',
    },
    Tag: {
      fontSize: 14,
      lineWidth: 0,
      borderRadiusSM: 4,
    },
    Message: {
      borderRadiusLG: 4,
    },
    Notification: {
      colorBgElevated: '#1f1f26',
      colorText: '#ffffff',
      width: 343,
      fontSize: 14,
      paddingContentHorizontalLG: 16,
      colorTextHeading: '#ffffff',
      colorIcon: '#666666',
      colorIconHover: '#ffffff',
    },
    Form: {
      itemMarginBottom: 8,
    },
  },
}

export default themeConfig
