export { default as LeftImg } from './LeftImg'
export { default as CheckComp } from './CheckComp'
export { default as EmailInput } from './EmailInput'
export { default as PhoneInput } from './PhoneInput'
export { default as VerificationCode } from './VerificationCodeInput'
export { default as PasswordInput } from './PasswordInput'
export { default as NotCode } from './NotCode'
export { default as SwitchTabs } from './SwitchTabs'
